version: "3.9"
services:
  token:
    container_name: belajardocker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:5000
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=dev