name: Pylint

on: [push]

jobs:
  check_with_pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install pylint
      run: |
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

  push_to_docker:
    needs: check_with_pylint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build
      - name: Create Tag DOcker and Stop containers
        if: always()
        run: |
          docker tag belajar_dasar_docker_app-dev:latest soegidev/belajardocker:latest
          docker-compose -f "docker-compose.yml" down --rmi local
      - name: docker login
        run: | # log into docker hub account
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push images to docker
        run: docker push soegidev/belajardocker:latest
  push_to_registry:
    needs: push_to_docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build
      - name: Create Tag DOcker and Stop containers
        if: always()
        run: |
          docker tag belajar_dasar_docker_app-dev:latest soegidev/belajar_dasar_docker:latest
          docker-compose -f "docker-compose.yml" down --rmi local
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Images Docker to Registry GITHUB
        run: |
          docker build . --tag ghcr.io/soegidev/belajar_dasar_docker:latest
          docker run ghcr.io/soegidev/belajar_dasar_docker:latest
          docker push ghcr.io/soegiedv/belajar_dasar_docker:latest
